Adattamento WebApp
4ourSquared/LumosMinima-code pull request #18
Opened 2023-08-16 16:32 UTC by matnut2

Riadattata la webapp alle informazioni ottenute tramite lo scambio di informazioni con il Sig. Patera

2023-08-16 17:16 UTC, matnut2 commented
Per @nicolasalberti00: per ora lasciamo stare gli errori dovuti alla _code duplication_, ci penseremo di nuovo quando almeno il sistema si reggerà in piedi

2023-08-16 17:18 UTC, nicolasalberti00 commented
Sisi, nel frattempo facciamolo andare, poi ripuliremo

2023-08-17 10:24 UTC, nicolasalberti00 requested changes
Valutiamo se effettivamente cambiare i nomi della funzionalità di interazione, secondo me un nome più specifico e non sbagliato grammaticamente è sinonimo di qualità e anche evita futuri fraintendimenti

2023-08-17 10:24 UTC, nicolasalberti00 commented on client/src/components/EditLampForm.tsx
> +    if (isLoading) {
Qui si può fare un banner figo, oppure semplicemente lasciarlo così, dato che non si vede praticamente

2023-08-17 10:24 UTC, nicolasalberti00 commented on client/src/components/EditLampForm.tsx
> +                    <label htmlFor="iter">Interazione</label>
Anche qui da modificare

2023-08-17 10:24 UTC, nicolasalberti00 commented on client/src/components/LampSingleView.tsx
> +            <li>Interazione: {lamp.iter}</li>
Anche qui come negli altri commenti

2023-08-17 10:24 UTC, nicolasalberti00 commented on client/src/components/SensorSingleView.tsx
> -// TODO: Implementare l'invio del segnale solo qualora il sensore sia in modalità automatica
Non ho capito se questi commenti vanno inseriti con l'altra PR o se vanno tolti con questa

2023-08-17 13:08 UTC, EricaCavaliere commented on client/src/components/EditLampForm.tsx
> +    if (isLoading) {
Io non ho notato finestre di caricamento. Se ci sono, da me durano molto poco, come se non ci fossero

2023-08-17 14:32 UTC, matnut2 commented on client/src/components/SensorSingleView.tsx
> -// TODO: Implementare l'invio del segnale solo qualora il sensore sia in modalità automatica
Vanno tolti già con questa, perchè temporalmente questa è nata dopo ma anticipa alcune modifiche di #16 .
Quindi che non ci siano va bene perchè i meccanismi sono già implementati, vanno solo collegati alle componenti, ma lo si farà poi

2023-08-17 14:34 UTC, matnut2 commented
> 

Ovviamente è uno stato embrionale. Le luci vengono impostate al massimo perchè manca una informazione che specifichi quanto devono accendersi i lampioni qualora venisse inviato il segnale di accensione. Si può sempre modificare, ma la struttura di base è quella.
Il pulsante di invio segnale semplicemente manda una richiesta al server come se tutti i lampioni fossero impostati su _push_, cosa che ovviamente va sistemata, ma in fase di test andava bene così. Quando il sistema sarà riadattato e avremo le idee più chiare dell'applicazione e sul come farla stare in piedi, si penserà ai dettagli.

2023-08-17 15:10 UTC, EricaCavaliere approved these changes

2023-08-19 17:10 UTC, nicolasalberti00 approved these changes
Ok ai nuovi cambiamenti

2023-08-20 13:55 UTC, merged